# Generated by Django 2.0 on 2018-01-11 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(max_length=15, primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='attributes',
            old_name='Att_id',
            new_name='att_id',
        ),
        migrations.RemoveField(
            model_name='product_ad',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='product_ad',
            name='cover_image',
            field=models.CharField(default='/bands/product_images/p1.jpg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_data',
            name='user_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AddField(
            model_name='images',
            name='product_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bands.Product_Ad'),
        ),
    ]
