# Generated by Django 2.0 on 2018-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_auto_20180111_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ad',
            name='state',
            field=models.CharField(default='Gujarat', max_length=20),
            preserve_default=False,
        ),
    ]
